// Code generated by "stringer -type=What"; DO NOT EDIT.

package what

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Reload-1]
	_ = x[Redirect-2]
	_ = x[Alert-3]
	_ = x[Inner-4]
	_ = x[Remove-5]
	_ = x[Insert-6]
	_ = x[Append-7]
	_ = x[Replace-8]
	_ = x[SAttr-9]
	_ = x[RAttr-10]
	_ = x[Value-11]
	_ = x[Trigger-12]
	_ = x[Hook-13]
	_ = x[Input-14]
	_ = x[Click-15]
}

const _What_name = "NoneReloadRedirectAlertInnerRemoveInsertAppendReplaceSAttrRAttrValueTriggerHookInputClick"

var _What_index = [...]uint8{0, 4, 10, 18, 23, 28, 34, 40, 46, 53, 58, 63, 68, 75, 79, 84, 89}

func (i What) String() string {
	if i >= What(len(_What_index)-1) {
		return "What(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _What_name[_What_index[i]:_What_index[i+1]]
}
