// Code generated by "stringer -type=What"; DO NOT EDIT.

package what

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Reload-1]
	_ = x[Redirect-2]
	_ = x[Alert-3]
	_ = x[Update-4]
	_ = x[Order-5]
	_ = x[Inner-6]
	_ = x[Remove-7]
	_ = x[Insert-8]
	_ = x[Append-9]
	_ = x[Replace-10]
	_ = x[SAttr-11]
	_ = x[RAttr-12]
	_ = x[Value-13]
	_ = x[Trigger-14]
	_ = x[Hook-15]
	_ = x[Input-16]
	_ = x[Click-17]
}

const _What_name = "NoneReloadRedirectAlertUpdateOrderInnerRemoveInsertAppendReplaceSAttrRAttrValueTriggerHookInputClick"

var _What_index = [...]uint8{0, 4, 10, 18, 23, 29, 34, 39, 45, 51, 57, 64, 69, 74, 79, 86, 90, 95, 100}

func (i What) String() string {
	if i >= What(len(_What_index)-1) {
		return "What(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _What_name[_What_index[i]:_What_index[i+1]]
}
