// Code generated by "stringer -type=What"; DO NOT EDIT.

package what

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Reload-1]
	_ = x[Redirect-2]
	_ = x[Alert-3]
	_ = x[Update-4]
	_ = x[Inner-5]
	_ = x[Remove-6]
	_ = x[Insert-7]
	_ = x[Append-8]
	_ = x[Replace-9]
	_ = x[SAttr-10]
	_ = x[RAttr-11]
	_ = x[Value-12]
	_ = x[Trigger-13]
	_ = x[Hook-14]
	_ = x[Input-15]
	_ = x[Click-16]
}

const _What_name = "NoneReloadRedirectAlertUpdateInnerRemoveInsertAppendReplaceSAttrRAttrValueTriggerHookInputClick"

var _What_index = [...]uint8{0, 4, 10, 18, 23, 29, 34, 40, 46, 52, 59, 64, 69, 74, 81, 85, 90, 95}

func (i What) String() string {
	if i >= What(len(_What_index)-1) {
		return "What(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _What_name[_What_index[i]:_What_index[i+1]]
}
