package jawstree

import (
	"net/http"
	"net/http/httptest"
	"path"
	"strconv"
	"strings"
	"testing"

	"github.com/linkdata/deadlock"
	"github.com/linkdata/jaws"
	"github.com/linkdata/jaws/lib/ui"
	"github.com/linkdata/staticserve"
)

// TestSetup_PrefixVariants verifies that for any prefix form (absolute, relative
// or empty) Setup neither panics nor diverges: every emitted asset URL appears in
// the head HTML and resolves to a registered handler.
func TestSetup_PrefixVariants(t *testing.T) {
	var names []string
	if err := staticserve.WalkDir(assetsFS, "assets", func(_ string, ss *staticserve.StaticServe) error {
		names = append(names, ss.Name)
		return nil
	}); err != nil {
		t.Fatal(err)
	}

	for _, prefix := range []string{"/static", "static", ""} {
		t.Run("prefix="+strconv.Quote(prefix), func(t *testing.T) {
			mux := http.NewServeMux()
			jw, err := jaws.New()
			if err != nil {
				t.Fatal(err)
			}
			defer jw.Close()

			if err := jw.Setup(mux.Handle, prefix, Setup); err != nil {
				t.Fatal(err)
			}

			rq := jw.NewRequest(nil)
			var sb strings.Builder
			if err := (ui.RequestWriter{Request: rq, Writer: &sb}).HeadHTML(); err != nil {
				t.Fatal(err)
			}
			head := sb.String()

			for _, name := range names {
				wantURI := staticserve.EnsurePrefixSlash(path.Join(prefix, name))
				if !strings.Contains(head, `"`+wantURI+`"`) {
					t.Errorf("head html missing %q", wantURI)
				}
				rr := httptest.NewRecorder()
				mux.ServeHTTP(rr, httptest.NewRequest(http.MethodGet, wantURI, nil))
				if rr.Code != http.StatusOK {
					t.Errorf("GET %q (prefix %q) = %d, want 200 (head URL must match a registered handler)", wantURI, prefix, rr.Code)
				}
			}
		})
	}
}

// TestNew_AssignsUniquePrivateKeys verifies that browser correlation identities
// are generated by the package rather than supplied by callers.
func TestNew_AssignsUniquePrivateKeys(t *testing.T) {
	var mu1, mu2 deadlock.RWMutex
	tree1, err := New(&mu1, &Node{})
	maybeError(t, err)
	tree2, err := New(&mu2, &Node{})
	maybeError(t, err)
	if tree1.key == "" || tree2.key == "" {
		t.Fatalf("empty generated keys: %q, %q", tree1.key, tree2.key)
	}
	if tree1.key == tree2.key {
		t.Fatalf("duplicate generated key %q", tree1.key)
	}
}

func TestMakeTreeKeyPanicsOnExhaustion(t *testing.T) {
	previous := nextTreeKey.Swap(^uint64(0))
	defer nextTreeKey.Store(previous)
	assertPanics(t, func() { makeTreeKey() })
}
