// Code generated by "stringer -type=What"; DO NOT EDIT.

package what

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Update-1]
	_ = x[Reload-2]
	_ = x[Redirect-3]
	_ = x[Alert-4]
	_ = x[Order-5]
	_ = x[Call-6]
	_ = x[separator-7]
	_ = x[Patch-8]
	_ = x[Inner-9]
	_ = x[Delete-10]
	_ = x[Replace-11]
	_ = x[Remove-12]
	_ = x[Insert-13]
	_ = x[Append-14]
	_ = x[SAttr-15]
	_ = x[RAttr-16]
	_ = x[SClass-17]
	_ = x[RClass-18]
	_ = x[Value-19]
	_ = x[Input-20]
	_ = x[Proposal-21]
	_ = x[Click-22]
	_ = x[ContextMenu-23]
	_ = x[Hook-24]
}

const _What_name = "InvalidUpdateReloadRedirectAlertOrderCallseparatorPatchInnerDeleteReplaceRemoveInsertAppendSAttrRAttrSClassRClassValueInputProposalClickContextMenuHook"

var _What_index = [...]uint8{0, 7, 13, 19, 27, 32, 37, 41, 50, 55, 60, 66, 73, 79, 85, 91, 96, 101, 107, 113, 118, 123, 131, 136, 147, 151}

func (i What) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_What_index)-1 {
		return "What(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _What_name[_What_index[idx]:_What_index[idx+1]]
}
